# minimalist prompt:  jhan :: ~/.dotfiles main »

add_newline = false
format = "$username[ :: ](#7c7c7c)$directory$git_branch$character"

[username]
show_always = true
style_user = "#d5c4a1"
format = "[$user]($style)"

[directory]
style = "#d5c4a1"
format = "[$path]($style) "
truncation_length = 3
truncate_to_repo = false

[git_branch]
format = "[$branch](#7c7c7c) "

[character]
success_symbol = "[»](#d5c4a1)"
error_symbol = "[»](#fb4934)"
