#!/bin/bash

# options=(
  # style=square
  # width=5.0
  # hidpi=on
  # active_color=0xff9aa5ce
  # inactive_color=0xff565f89
  # background_color=0xff1a1b26
# )

options=(
  style=square
  width=5.0
  hidpi=on
  active_color=0xff7aa2f7
  inactive_color=0xff414868
  background_color=0xff1f2335
)

borders "${options[@]}"
