#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

# kolory tokyo night
BG=0xe61a1b26
BG2=0xff292e42
FG=0xffc0caf5
BLUE=0xff7aa2f7
PURPLE=0xffbb9af7
GREEN=0xff9ece6a
GREY=0xff565f89

sketchybar --bar position=top height=32 margin=8 y_offset=4 corner_radius=10 \
  color=$BG blur_radius=20

sketchybar --default \
  padding_left=5 padding_right=5 \
  icon.font="JetBrainsMono Nerd Font:Bold:15.0" \
  label.font="JetBrainsMono Nerd Font:Bold:13.0" \
  icon.color=$FG label.color=$FG \
  icon.padding_left=4 icon.padding_right=4 \
  label.padding_left=4 label.padding_right=4

# spaces
for i in 1 2 3 4 5 6 7 8 9
do
  sketchybar --add space space.$i left \
    --set space.$i space=$i \
      icon=$i \
      icon.color=$GREY \
      icon.highlight_color=$BLUE \
      background.color=$BG2 \
      background.corner_radius=6 \
      background.height=22 \
      background.drawing=off \
      label.drawing=off \
      script="$PLUGIN_DIR/space.sh" \
      click_script="yabai -m space --focus $i"
done

# aktywna apka
sketchybar --add item front_app left \
  --set front_app icon.drawing=off label.color=$PURPLE \
    script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

# prawa strona
sketchybar --add item clock right \
  --set clock update_freq=30 icon.drawing=off label.color=$BLUE \
    script="$PLUGIN_DIR/clock.sh" \
  --add item battery right \
  --set battery update_freq=120 icon.color=$GREEN \
    script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change \
  --add item volume right \
  --set volume icon.color=$PURPLE \
    script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change

sketchybar --update
